securestore/DispFile/urls.py
from django.urls import path, include
from . import views
app_name= 'DispFile'
urlpatterns = [
    path('',views.home,name="home"),
    path('help/',views.Help,name="help"),
    path('contactus/',views.ContactUs,name="contactus"),
    path('aboutus/',views.AboutUs,name="aboutus"),
    path('viewprofile/',views.viewprofile,name="viewprofile"),
    path('viewprofile/editprofile/',views.edit_profile,name="editprofile"),
    path('viewprofile/password/', views.change_password, name='change_password'),
    path('recent/', views.recent, name="Recent"),
    path('sharedwithme/', views.sharedwithme, name="sharedwithme"),

]

securestore/blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import url, include
app_name = "blog"
urlpatterns = [
    path('admin/', admin.site.urls),
    url('^#', include('django.contrib.auth.urls')),
    path('', views.main_page, name='main_page'),
]

securestore/emailtest/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from login_signup import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.main,name='main'),
    url(r'^login_signup/',include('login_signup.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url('^',include('django.contrib.auth.urls')),
]

securestore/securestore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('DispFile.urls')),
    path('', include('login_signup.urls')),
    path('mainupload/', include('mainupload.urls')),
    url('^', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

securestore/DispFile/models.py
from django.db import models

# Create your models here.

securestore/DispFile/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    username = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=300, help_text='Required')
   
    class Meta():
        model = User
        fields = ('username','email')


    def save(self, user=None):
        user_profile=super(UserForm, self).save(commit=False)
        if user:
            user_profile.user=user
        user_profile.save()
        return user_profile 

securestore/DispFile/views.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import DetailView
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import DetailView
from django.contrib import messages
from DispFile.forms import UserForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from mainupload.models import *

# Create your views here.


@csrf_exempt
class IndexView(DetailView):
    model = User

    template_name = 'LoginHome.html'


@login_required
def home(request):
    user = request.user
    context = {user: user}
    return render(request, 'LoginHome.html', context=context)


@login_required
def Help(request):
    return render(request, 'LoginHelp.html')


@login_required
def AboutUs(request):
    return render(request, 'LoginAboutUs.html')


@login_required
def ContactUs(request):
    return render(request, 'LoginContactUs.html')


@login_required
def viewprofile(request):
    args = {'user': request.user}

    return render(request, 'viewprofile.html', args)


@login_required
def edit_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)

        if user_form.is_valid():
            user_form.save()

            messages.success(
                request, ('Your profile was successfully updated!'))

            return redirect('DispFile:viewprofile')
        else:
            messages.error(request, ('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)

    return render(request, 'edit_profile.html', {
        'user_form': user_form,

    })


@login_required
def change_password(request):

    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Imp
            messages.success(
                request, 'Your password was successfully updated!')
            return redirect('DispFile:viewprofile')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'change_password.html', {
        'form': form
    })


@csrf_exempt
def recent(request):
    user = request.user
    print(user)
    files = [f for f in File.objects.all() if f.get_user() == user]
    files.sort(key=lambda file: file.uploaded)
    files.reverse()
    files = files[:5]
    res = []
    for i in files:
        res.append({
            'name': i.name(),
            'pk': i.pk,
            'protected': i.protected
        })
    return JsonResponse(res, safe=False)


@csrf_exempt
def sharedwithme(request):
    user = request.user
    print(user)
    files = [f for f in SharedFiles.objects.all() if f.User == user]
    print(files)
    res = []
    for i in files:
        res.append({
            'name': i.File.name(),
            'pk': i.File.pk,
            'protected': i.File.protected
        })
    return JsonResponse(res, safe=False)

securestore/DispFile/templates/LoginAboutUs.html
{% extends 'LoginBase.html' %}

{% block content %}
<h2> About Us </h2>
<p>Info about the comapany</p>
<script>
  $(document).ready(function() {
    $("#SideNavBar").empty()
    });
</script>
{% endblock %}

securestore/DispFile/templates/LoginContactUs.html
{% extends 'LoginBase.html' %}

{% block content %}
<!-- <h2> ContactUs </h2>
<p>Contact and Emails</p> -->
<script>
  $(document).ready(function() {
    $("#SideNavBar").empty()
    });
</script>
<div class="container">

<h3>Tell us what we can change.</h3>
<br>
<br>
<div class="row">
  <div class="col-sm-4">
    <h5>Siddartha Mishra</h5>
    <p>siddartha.m17@iiits.in</p>
    </div>
    <div class="col-sm-4">
      <h5>Subh Vanvat</h5>
      <p>subh.v17@iiits.in</p>
      </div>
      <div class="col-sm-4">
        <h5>Somana Rupesh</h5>
        <p>venkatasaikrishnarupesh.s17@iiits.in</p>
        </div>
  </div>
<br>
<br>
<br>
<br>
<br>

  <div class="row">
    <div class="col-sm-4">
      <h5> Swathi Sindhu</h5>
      <p>swathi.s17@iiits.in</p>
      </div>
      <div class="col-sm-4">
        <h5> Abhinay Krishna</h5>
        <p>abhinay.k17@iiits.in</p>
        </div>
        <div class="col-sm-4">
          <h5>Sakir Shah</h5>
          <p>sakir.s17@iiits.in</p>
          </div>
    </div>
  </div>
{% endblock %}

securestore/DispFile/templates/LoginHelp.html
{% extends 'LoginBase.html' %}

{% block content %}
<h2>Help </h2>
<p>Any Queries and reportings etc</p>
<script>
  $(document).ready(function() {
    $("#SideNavBar").empty()
    });
</script>
{% endblock %}

securestore/DispFile/templates/LoginRecent.html
{% extends 'LoginBase.html' %}

{% block content %}
<h2> Here Recent are shown</h2>
<p>recent files</p>

{% endblock %}

securestore/DispFile/templates/LoginStorage.html
{% extends 'LoginBase.html' %}

{% block content %}
<h2> Storage </h2>
<div id="storageLeft">
<p>Storage of user is shown</p>

{% endblock %}

securestore/DispFile/templates/change_password.html
{% extends 'LoginBase.html' %}
{% load crispy_forms_tags %}
{% block content %}


     
      <h1>Change Your Password</h1>
      <div>
          <form method="post">
                {% csrf_token %}
                {{ form|crispy }}<br>
                <button type="submit">Submit</button>
          </form>
          <br>
      </div>
      </div>
{% endblock %}

securestore/DispFile/templates/edit_profile.html
{% extends 'LoginBase.html' %}

{% block content %}
      
      <h1>Edit Your Profile</h1>
      <div>
          <form method="POST"enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p}}
                <button type="submit" >Submit</button>      
          </form>
          <br>
      </div>
{% endblock %}

securestore/DispFile/templates/viewprofile.html
{% extends 'LoginBase.html' %}

{% block content %}


<div class="container">
    <h1>User Profile</h1>
          <p>Username: {{ user }}</p>
          <p>Email :  {{ user.email }}</p>
         <br>
          <a href="{% url 'DispFile:editprofile' %}">Edit Profile</a><br>
          <a href="{% url 'DispFile:change_password' %}">Change your password here !</a>
         
    </div>
<script>
  $(document).ready(function() {
    $("#SideNavBar").empty()
    });
    
</script>
{% endblock %}