securestore/blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import url, include
app_name = "blog"
urlpatterns = [
    path('admin/', admin.site.urls),
    url('^#', include('django.contrib.auth.urls')),
    path('', views.main_page, name='main_page'),
]

securestore/emailtest/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from login_signup import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.main,name='main'),
    url(r'^login_signup/',include('login_signup.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url('^',include('django.contrib.auth.urls')),
]

securestore/login_signup/urls.py
from django.conf.urls import url

from login_signup import views
from django.urls import path, re_path
import DispFile.views
from rest_framework.authtoken import views as rest_views

app_name = 'login_signup'
urlpatterns = [
    url(r'^api-token-auth/', rest_views.obtain_auth_token),
    path('home', DispFile.views.home, name='home'),
    url('signup/', views.signup, name='signup'),
    url('logout/', views.user_logout, name='logout'),
    url('login', views.user_login, name='user_login'),
    url(
        r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),

]

securestore/securestore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('DispFile.urls')),
    path('', include('login_signup.urls')),
    path('mainupload/', include('mainupload.urls')),
    url('^', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

securestore/templates/LoginBase.html
<!Doctype html>
{% load staticfiles %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"> -->
  <link href="http://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <style>
    @import url(http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css);

.navi2 {
    margin-bottom: 0;
    border: 0;
    font-family: Montserrat, sans-serif;
    font-size: 15px !important;
    letter-spacing: 4px;
    border-radius: 0;
    background-color: #e2dcdc;
}
  }
  .navbar li a,
  .navbar .navbar-brand {
  }
  .flex-sm-column a:hover{
   background-color: black !important;
}
.flex-sm-column button:hover{
 background-color: black !important;
}
  .navbar-nav li a:hover
{
    background-color: black !important;
}

  .navbar-default .navbar-toggle {
    border-color: transparent;
    color: white;
  }
  body{
    margin-top:20px;
    }

    .btn2 {
      background-color: lightgrey;
      border: none;
      color: black;
      padding: 10px 50px ;
      font-size: 16px;
      cursor: pointer;
  }

  /* Darker background on mouse-over */
  .btn2:hover {
      background-color: RoyalBlue;
  }
  </style>
</head>

<body class="bg-light">



  <div class="container-fluid">
    <div class="row">

      <div class="col-sm-12 ">
        <nav class="navbar navbar-expand-sm  navbar-light navi2">
          <a class="navbar-brand" href="/Home"><img src="{% static 'logo2.jpg' %}" alt="Logo" style="width:60px;"></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar6" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse justify-content-stretch" id="navbar6">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="/Home"><span class="text-muted">Home</span></a>
              </li>
            </ul>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="/Home/help"><span class="text-muted">Help</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/Home/aboutus"><span class="text-muted">About</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/Home/contactus"><span class="text-muted">Contact us</span></a>
              </li>
            </ul>

          </div>

        </nav>
        <hr>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-2">
        <nav class="navbar navbar-light navbar-expand-sm px-0 ">
          <!--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarWEX" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>-->
          <div id="navbarWEX">
            <div class="flex-sm-column ">
              <div class="btn-group-vertical">
                <button type="button" class="btn btn-light btn-block text-left" data-toggle="modal" data-target="#exampleModal"><span class="text-muted">File Upload</span></button>
                <button type="button" class="btn btn-light btn-block text-left " data-toggle="modal" data-target="#exampleModal2"><span class="text-muted">Add Directory</span></button>
              </div>
              <a class="nav-item nav-link active" href="/Home"><span class="text-muted">Home</span></a>
              <a href="/Home/recent" class="nav-item nav-link"><span class="text-muted">Recent</span></a>
              <hr>
              <a href="#" class="nav-item nav-link"><span class="text-muted">Backup</span></a>
              <hr>
              <a href="/Home/storage" class="nav-item nav-link"><span class="text-muted">Storage</span></a>
              <ul style="list-style:none;" class="nav-item">
                <li class="nav-item"> storage is shown</li>
                <li>
                  <a style="font-size:15px" class="nav-item" href="#">UPGRADE STORAGE</a>
                </li>
              </ul>
              <div class="btn-group-vertical">
              </div>
            </div>
          </div>
        </nav>
      </div>

      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">File Upload</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form>
                <div class="form-group">
                  <p>Default file:</p>
                  <input type="file" class="col-form-label" id="input-file" name="filename2" multiple>
                  <br>
                  <br>
                  <label for="name" class="col-form-label">File Name:</label>
                  <br>

                  <input type="text" id="file-name" class="form-control" placeholder="Enter FileName" required>
                  <div id="ShowHide">
                    <label for="password" class="col-form-label">Password:</label>
                    <input type="password" class="form-control" placeholder="Enter Password" name="psw" required>
                  </div>
                  <br>
                  <label class="radio-inline" for="yes">
                    <input type="radio" name="optradio" id="yes" value="option1" checked>Secured
                  </label>
                  <label class="radio-inline" for="no">
                    <input type="radio" name="optradio" id="no" value="option2">NotSecured
                  </label>
                </div>
              </form>

            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" id="new" data-dismiss="modal">Create</button>
              <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
            </div>
          </div>
        </div>
      </div>

      <div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel2" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Directory Name</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form>
                <div class="form-group">
                  <label for="Dirname" class="col-form-label">Directory Name:</label>
                  <input type="text" id="dir-name" class="form-control" placeholder="name" required>
                </div>
              </form>

            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" id="newDirec" data-dismiss="modal">Create</button>
              <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-8" id="clearRow">
        {%block content %}

        {%endblock%}
      </div>
    </div>

  </div>
</body>

</html>

securestore/templates/login.html
<!DOCTYPE html>
<html>
<head>
<style>
form {
    border: 3px solid black;
}
body{
color:teal;
}
input[type="text"], input[type="password"] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid black;
    box-sizing: border-box;
    color:white;
    }
input[type="text"],input[type="password"],textarea{
        background-color:#5F6367;
        opacity:0.1;
        color:white;
}
button:hover {
    opacity: 0.5;
}
.cancelbtn {
    border: none;
    margin: 8px 0;
    width: auto;
    padding: 15px 30px;
    color: white;
    background-color: teal;
}
@media screen and (max-width: 300px) {
    span.psw {
        display: block;
        float: none;
    }
    .cancelbtn {
        width: 100%;
    }
}
.modal-content {
    padding-left:20px;
    padding-right:20px;
    padding-bottom: 20px;
    background-color:rgba(0,0,0,0.9);
    opacity =0.6;
    margin: 5px auto;
    border: 1px solid black;
    width: 18%;
}
.animate {
    -webkit-animation: animatezoom 0.6s;
    animation: animatezoom 0.6s
}
@-webkit-keyframes animatezoom {
    from {-webkit-transform: scale(0)}
    to {-webkit-transform: scale(1)}
}
@keyframes animatezoom {
    from {transform: scale(0)}
    to {transform: scale(1)}
}
</style>
</head>
<body>
<b>
<br><br><br><br><br><br><br><br>
<form method="post" class="modal-content animate " font-size="20px"; action="{% url 'login_signup:user_login' %}"   >
  <br>
{% csrf_token %}
{{ user_form.as_p }}
  <center><h2>Login</h2></center>
  <br for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
  <label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
  <div >
  <br>
      <center>
      <button type="button" onclick= location.href="{% url 'login_signup:main' %}" class="cancelbtn">Cancel</button>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <button type="submit"  class="cancelbtn" >Login</button>
      </center>
    </div>
</form>
</b>
</body>
</html>

securestore/templates/logo.html
<html>
<head>
<title>
Secure Store</title>
<link rel="shortcut icon" type="image/png" href="img/favicon.png">

<style>
body{
background-image:url(/static/giphy.gif);
background-attachment:fixed;
background-position:center;
background-color:#000;
background-repeat: no-repeat;
}
.padd
{
padding-top:240px;
}
</style>
<meta http-equiv="refresh" content="3; url=index.html">
</head>
<body>
<center>
<font color="54faf2">
<div class="padd">

</div>
</font>
</center>
</body>
</html>