securestore/blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import url, include
app_name = "blog"
urlpatterns = [
    path('admin/', admin.site.urls),
    url('^#', include('django.contrib.auth.urls')),
    path('', views.main_page, name='main_page'),
]

securestore/emailtest/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from login_signup import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.main,name='main'),
    url(r'^login_signup/',include('login_signup.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url('^',include('django.contrib.auth.urls')),
]

securestore/login_signup/urls.py
from django.conf.urls import url

from login_signup import views
from django.urls import path, re_path
import DispFile.views
from rest_framework.authtoken import views as rest_views

app_name = 'login_signup'
urlpatterns = [
    url(r'^api-token-auth/', rest_views.obtain_auth_token),
    path('home', DispFile.views.home, name='home'),
    url('signup/', views.signup, name='signup'),
    url('logout/', views.user_logout, name='logout'),
    url('login', views.user_login, name='user_login'),
    url(
        r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),

]

securestore/securestore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('DispFile.urls')),
    path('', include('login_signup.urls')),
    path('mainupload/', include('mainupload.urls')),
    url('^', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

securestore/login_signup/models.py
from django.db import models
from django.contrib.auth.models import User

from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

# Create your models here


class UserData(models.Model):
    email = models.EmailField(max_length=200, help_text='Required')
    name = models.CharField(max_length=200)
    password = models.CharField(max_length=200)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

securestore/login_signup/forms.py
from django import forms
from django.contrib.auth.models import User
class UserForm(forms.ModelForm):
    username = forms.CharField(min_length=6,max_length=100)
    email = forms.EmailField(max_length=200)
    password = forms.CharField(min_length=6,widget=forms.PasswordInput())
    confirm_password = forms.CharField(min_length=6,widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

securestore/login_signup/views.py
from django.shortcuts import render, redirect
from login_signup.forms import UserForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib import auth
from django.contrib.auth import login, authenticate
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from .models import UserData
import requests
from mainupload.models import RootDirectory
from django.contrib.auth.decorators import login_required
from django.contrib import messages

def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('blog:main_page'))



def signup(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid()and user_form.cleaned_data['password'] == user_form.cleaned_data['confirm_password']:
            user = user_form.save(commit=False)
            user.is_active = False
            user.set_password(user.password)
            user.save()
            registered = True
            current_site = get_current_site(request)
            domain = current_site.domain
            print(domain)
            message = render_to_string('acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })
            to_email = user_form.cleaned_data.get('email')
            name = user_form.cleaned_data.get('username')
            password = user_form.cleaned_data.get('password')
            print(name)
            print(password)
            response = requests.get(
                "http://api.quickemailverification.com/v1/verify?email=" + to_email + "&apikey=15aef1e3ebf4f0e3357b6aab94bb77833e639fc261b2d32903e1895bd330")
            result = response.json()

            if (result['did_you_mean'] == '' and result['result'] == "valid"):
                print("valid")
                userdata = UserData.objects.create(
                    email=to_email, name=name, password=password)
                userdata.save()
                mail_subject = 'Activate your blog account.'
                to_email = user_form.cleaned_data.get('email')
                email = EmailMessage(mail_subject, message, to=[to_email])
                email.send()
                return render(request, 'login_signup/emailsent.html', {})

            else:
                try:
                    u = User.objects.get(username=name)
                    u.delete()
                except User.DoesNotExist:
                    return HttpResponse('The email given is invalid please check it ')
                except Exception as e:
                    return render(request, 'login_signup/signup.html', {'user_form': user_form})
                return HttpResponse('The email given is invalid please check it ')
        elif user_form.data['password'] != user_form.data['confirm_password']:
                 user_form.add_error('confirm_password', 'The passwords do not match')
       
    else:
        user_form = UserForm()
    return render(request, 'login_signup/signup.html', {'user_form': user_form, 'registered': registered})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        RootDirectory.objects.create(User=user)
        return HttpResponseRedirect(reverse( 'DispFile:home'))

    else:
        return HttpResponse('Activation link is invalid!')


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('DispFile:home'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            messages.error(request, 'username or password is not correct')
            return render(request, 'login_signup/login.html', {})
    else:
        return render(request, 'login_signup/login.html', {})

securestore/login_signup/templates/login_signup/emailsent.html
<!DOCTYPE html>
<html>
<head>
<style>
* {
	margin: 0px;
	padding: 0px;
	box-sizing: border-box;
}

body, html {
	height: 100%;
	font-family: Poppins-Regular, sans-serif;
}


.limiter {
  width: 100%;
  margin: 0 auto;
}

.container-login100 {
  width: 100%;
  min-height: 100vh;
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  align-items: center;
  padding: 5px;
   background: #9053c7;
  background: -webkit-linear-gradient(-135deg, #c850c0, #4158d0);
  background: -o-linear-gradient(-135deg, #c850c0, #4158d0);
  background: -moz-linear-gradient(-135deg, #c850c0, #4158d0);
  background: linear-gradient(-135deg, #c850c0, #4158d0);
}

.login100-form-title {
  font-family: Poppins-Bold;
  font-size: 24px;
  color: #333333;
  line-height: 1.2;
  text-align: center;

  width: 100%;
  display: block;
  padding-bottom: 54px;
}

.wrap-login100 {
  width: 500px;
  background: #fff;
  border-radius: 10px;
  overflow: hidden;

  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  padding: 50px 100px 30px 90px;
}

</style>
</head>
<body>
<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
<span class="login100-form-title">
                                      Please click on the link sent to your mail to activate your account
              </span>
  <br><br>
</div>
</div>
</div>
</body>
</html>

securestore/login_signup/templates/login_signup/login.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>

* {
	margin: 0px;
	padding: 0px;
	box-sizing: border-box;
}

body, html {
	height: 100%;
	font-family: Poppins-Regular, sans-serif;
}

/*---------------------------------------------*/
a {
	font-family: Poppins-Regular;
	font-size: 14px;
	line-height: 1.7;
	color: #666666;
	margin: 0px;
	transition: all 0.4s;
	-webkit-transition: all 0.4s;
  -o-transition: all 0.4s;
  -moz-transition: all 0.4s;
}

a:focus {
	outline: none !important;
}

a:hover {
	text-decoration: none;
  color: #57b846;
}

/*---------------------------------------------*/
h1,h2,h3,h4,h5,h6 {
	margin: 0px;
}

p {
	font-family: Poppins-Regular;
	font-size: 14px;
	line-height: 1.7;
	color: #666666;
	margin: 0px;
}

ul, li {
	margin: 0px;
	list-style-type: none;
}


/*---------------------------------------------*/
input {
	outline: none;
	border: none;
}

textarea {
  outline: none;
  border: none;
}

textarea:focus, input:focus {
  border-color: transparent !important;
}

input:focus::-webkit-input-placeholder { color:transparent; }
input:focus:-moz-placeholder { color:transparent; }
input:focus::-moz-placeholder { color:transparent; }
input:focus:-ms-input-placeholder { color:transparent; }

textarea:focus::-webkit-input-placeholder { color:transparent; }
textarea:focus:-moz-placeholder { color:transparent; }
textarea:focus::-moz-placeholder { color:transparent; }
textarea:focus:-ms-input-placeholder { color:transparent; }

input::-webkit-input-placeholder { color: #999999; }
input:-moz-placeholder { color: #999999; }
input::-moz-placeholder { color: #999999; }
input:-ms-input-placeholder { color: #999999; }

textarea::-webkit-input-placeholder { color: #999999; }
textarea:-moz-placeholder { color: #999999; }
textarea::-moz-placeholder { color: #999999; }
textarea:-ms-input-placeholder { color: #999999; }

/*---------------------------------------------*/
button {
	outline: none !important;
	border: none;
	background: transparent;
}

button:hover {
	cursor: pointer;
}

iframe {
	border: none !important;
}


/*//////////////////////////////////////////////////////////////////
[ Utility ]*/

.txt2 {
  font-family: Poppins-Regular;
  font-size: 13px;
  line-height: 1.5;
  color: green;
}


/*//////////////////////////////////////////////////////////////////
[ login ]*/

.limiter {
  width: 100%;
  margin: 0 auto;
}

.container-login100 {
  width: 100%;
  min-height: 100vh;
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  align-items: center;
  padding: 5px;
   background: #9053c7;
  background: -webkit-linear-gradient(-135deg, #c850c0, #4158d0);
  background: -o-linear-gradient(-135deg, #c850c0, #4158d0);
  background: -moz-linear-gradient(-135deg, #c850c0, #4158d0);
  background: linear-gradient(-135deg, #c850c0, #4158d0);
}

.wrap-login100 {
  width: 850px;
  background: #fff;
  border-radius: 10px;
  overflow: hidden;

  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  padding: 100px 100px 30px 90px;
}

/*------------------------------------------------------------------
[  ]*/
.login100-pic {
  width: 250px;
}

.login100-pic img {
  max-width: 100%;
}


/*------------------------------------------------------------------
[  ]*/
.login100-form {
  width: 290px;
}

.login100-form-title {
  font-family: Poppins-Bold;
  font-size: 24px;
  color: #333333;
  line-height: 1.2;
  text-align: center;

  width: 100%;
  display: block;
  padding-bottom: 54px;
}


/*---------------------------------------------*/
.wrap-input100 {
  position: relative;
  width: 100%;
  z-index: 1;
  margin-bottom: 10px;
}

.input100 {
  font-family: Poppins-Medium;
  font-size: 15px;
  line-height: 1.5;
  color: #666666;

  display: block;
  width: 100%;
  background: #e6e6e6;
  height: 50px;
  border-radius: 25px;
  padding: 0 30px 0 68px;
}


/*------------------------------------------------------------------
[ Focus ]*/
.focus-input100 {
  display: block;
  position: absolute;
  border-radius: 25px;
  bottom: 0;
  left: 0;
  z-index: -1;
  width: 100%;
  height: 100%;
  box-shadow: 0px 0px 0px 0px;
  color: rgba(87,184,70, 0.8);
}

.input100:focus + .focus-input100 {
  -webkit-animation: anim-shadow 0.5s ease-in-out forwards;
  animation: anim-shadow 0.5s ease-in-out forwards;
}

@-webkit-keyframes anim-shadow {
  to {
    box-shadow: 0px 0px 70px 25px;
    opacity: 0;
  }
}

@keyframes anim-shadow {
  to {
    box-shadow: 0px 0px 70px 25px;
    opacity: 0;
  }
}

.symbol-input100 {
  font-size: 15px;

  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  align-items: center;
  position: absolute;
  border-radius: 25px;
  bottom: 0;
  left: 0;
  width: 100%;
  height: 100%;
  padding-left: 35px;
  pointer-events: none;
  color: #666666;

  -webkit-transition: all 0.4s;
  -o-transition: all 0.4s;
  -moz-transition: all 0.4s;
  transition: all 0.4s;
}

.input100:focus + .focus-input100 + .symbol-input100 {
  color: #57b846;
  padding-left: 28px;
}

/*------------------------------------------------------------------
[ Button ]*/
.container-login100-form-btn {
  width: 100%;
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  padding-top: 20px;
}

.login100-form-btn {
  font-family: Montserrat-Bold;
  font-size: 15px;
  line-height: 1.5;
  color: #fff;
  text-transform: uppercase;

  width: 100%;
  height: 50px;
  border-radius: 25px;
  background: #57b846;
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 0 25px;

  -webkit-transition: all 0.4s;
  -o-transition: all 0.4s;
  -moz-transition: all 0.4s;
  transition: all 0.4s;
}

.login100-form-btn:hover {
  background: forestgreen;
}



/*------------------------------------------------------------------
[ Responsive ]*/



@media (max-width: 992px) {
  .wrap-login100 {
    padding: 177px 90px 33px 85px;
  }

  .login100-pic {
    width: 35%;
  }

  .login100-form {
    width: 50%;
  }
}

@media (max-width: 768px) {
  .wrap-login100 {
    padding: 100px 80px 33px 80px;
  }

  .login100-pic {
    display: none;
  }

  .login100-form {
    width: 100%;
  }
}

@media (max-width: 576px) {
  .wrap-login100 {
    padding: 100px 15px 33px 15px;
  }
}



</style>
</head>
<body >
<div class="limiter" >
		<div class="container-login100" >
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<br><br><br><img src="https://fboverlays.com/pages/assets/frontend/img/previewImage.png" alt="IMG">
				</div>
                
                <form method="post" class="login100-form" font-size="20px"; action="{% url 'login_signup:user_login' %}"   >
                  <br>
                  {% csrf_token %}
                        <span class="login100-form-title">
                                        <h2>User Login</h2>
                        </span>

                  <div class="wrap-input100 " >
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100"></span>
				  </div>

                  <div class="wrap-input100" >
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100"></span>
				   </div>

                  <div class="container-login100-form-btn">
						<button class="login100-form-btn" type="submit">
							Login
						</button>
					</div><br>

					<div class="text-center p-t-12">
                        	<a class="txt2" href="{% url 'blog:password_reset' %}">
                                    Forgot Password?
                                </a>
						
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
						<a class="txt2" href="{% url 'blog:main_page' %}">
							Cancel
						</a>
					</div><br>
        <br><br>

        <br>
        {% for message in messages %}

                    <div class="alert alert-success">

                        {{ message }}

                    </div>
            {% endfor %}
                </form>
            </div>
        </div>
    </div>
</body>
</html>

securestore/login_signup/templates/login_signup/main.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
     <style>
button {
    background-color: teal;
    color: white;
    padding: 1px 2px;
    margin: 5px 0;
    border: none;
    cursor: pointer;
    width: 10%;
}
button:hover {
    opacity: 0.8;
}
</style>
  </head>
  <body>
{% if user.is_authenticated %}
  <p><button onclick=location.href="{% url 'logout' %}" ><h4>logout</h4></button></p>
{% else %}
  <button onclick=location.href="{% url 'login_signup:user_login' %}"><h4>Login</h4></button>
  <button onclick=location.href="{% url 'login_signup:signup' %}" ><h4>Signup</h4></button>
{% endif %}
  </body>
</html>

securestore/login_signup/templates/login_signup/signup.html
<!DOCTYPE html>
<html>
<head>
<style>
body{
color:teal;
}
input[type="text"], input[type="password"],input[type="email"]{
    color:teal;
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid black;
    box-sizing: border-box;
    }
input[type="text"],input[type="password"],input[type="email"],textarea{
        background-color:teal;

        color:black;
}
button {
  background-color: teal;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 40%;
  opacity: 0.9;
}
button:hover {
  opacity:0.7;
}
.container {
  padding: 16px;
}
.modal-content {
  background-color:rgba(0,0,0,0.9);
  margin: 5% auto 15% auto;
  border: 1px solid teal;
  width: 30%;
}
hr {
  border: 1px solid teal;
  margin-bottom: 25px;
}
.clearfix::after {
  content: "";
  clear: both;
  display: table;
}
.animate {
    -webkit-animation: animatezoom 0.6s;
    animation: animatezoom 0.6s
}
@-webkit-keyframes animatezoom {
    from {-webkit-transform: scale(0)}
    to {-webkit-transform: scale(1)}
}
@keyframes animatezoom {
    from {transform: scale(0)}
    to {transform: scale(1)}
}
</style>
</head>
<body>
  <form method="post" class="modal-content animate" action="{% url 'login_signup:signup' %}">
    <div class="container">
    <center><h2>Signup</h2></center>
    {% csrf_token %}
    {{ user_form.as_p }}
    <div class="clearfix">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   <button type="submit" onsubmit=location.href="{% url 'login_signup:home'%}">Sign Up</button>"
        <button type="button" onclick=location.href="{% url 'blog:main_page' %}"  class="cancelbtn">Cancel</button>
        &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;



      </div>
    </div>
  </form>
</body>
</html>